enum WhiteboardEnum {
    FREE_DRAW = "FD",
    CHINESE_BRUSH = "CB",
    HIGHLIGHTER = "HIL",
    SLIDE_CHANGE = "SC",
    DELETE = "DEL",
    PATH_ERASE = "PE",
    UNDO = "UN",
    REDO = "RE",
    RECTANGLE_DRAW = "REC",
    CIRCLE_DRAW = "CIR",
    TRIANGLE_DRAW = "TRI",
    ELLIPSE_DRAW = "ELL",
    STAR_DRAW = "STR",
    IMAGE = "IMG",
    STRAIGHT_LINE = "SL",
    ARROW = "ARR",
    FILL_SHAPE = "FLS",
    FILL_BACKGROUND = "FLB",
    STROKE_COLOR = "STC",
    RESIZE = "RES",
    OBJECT_MOVE = "OBM",
    CLEAR_ALL = "CA",
    PARALLELOGRAM_DRAW = "PLL",
    TRAPEZIUM_DRAW = "TPZ",
    CLONE = "CLO",
    PDF_IMAGE = "PDI",
    FILL_TEMPLATE_COLOR = "FTC",
    BACKGROUND_IMAGE = "BGI",
    FETCH_EVENTS = "FE",
}

export { WhiteboardEnum };
